### ISSUE TITLE
Add support for traits in Query filters

### ISSUE THREAD

**Issue by dbidwell94** [JoJoJet/bevy-trait-query#50]
In my particular use case, I would like the ability to be able to use traits in a `With<>` or `Without<>` filter in the query.

Example:
```rust
pub fn cleanup_status(
    mut commands: Commands,
    q: Query<
        Entity,
        (
            With<PawnStatus<pawn_status::Attacking>>,
            Without<dyn work_order::OrderItem>,
        ),
    >,
) {
}
```

The above return a compile error because 
- the size for values of type (dyn OrderItem + 'static) cannot be known at compilation time the trait `Sized` is not implemented for `(dyn OrderItem + 'static)`
- the trait bound `(dyn OrderItem + 'static): bevy::prelude::Component` is not satisfied
the following other types implement trait `bevy::prelude::Component`

The definition for `OrderItem` is as such:
```rust
    #[bevy_trait_query::queryable]
    pub trait OrderItem {}
```

**Comment by RobWalt** [comment]
The desired behavior should be achievable with the results from #55 and #58 . Instead of using the native `With` and `Without` filters, you should be able to use `WithOne` and `WithoutOne` to get the same result. If I'm missing a case, let me know!

**Comment by RobWalt** [comment]
This feature is now supported as of `bevy-trait-query` `v0.6.0`!

Please see [`WithoutAny`](https://docs.rs/bevy-trait-query/latest/bevy_trait_query/one/struct.WithoutAny.html) for details
