### ISSUE TITLE
Bevy 0.13.0 Compatibility

### ISSUE THREAD

**Issue by bennoinbeta** [JoJoJet/bevy-trait-query#54]
The release of Bevy `0.13.0` includes changes like ([Bevy PR #9918](https://github.com/bevyengine/bevy/pull/9918)) that affect `bevy-trait-query`. These updates likely require adjustments beyond a simple version bump.

Could we look into updating `bevy-trait-query` for Bevy `0.13.0` support? This would ensure continued compatibility for users relying on both.

In attempting to upgrade the crate for Bevy 0.13.0 compatibility and submitting a PR ([#53](https://github.com/JoJoJet/bevy-trait-query/pull/53)), I realized the update entails more than a straightforward version bump due to intricacies in Bevy's Query system that I'm not yet familiar with.

**Comment by RobWalt** [comment]
I think this can be closed

**Comment by bennoinbeta** [comment]
Thanks @RobWalt   🙌
